#ifndef ESP32_FAST_INT_H
#define ESP32_FAST_INT_H

#define CPU_INT_NMI	14

#ifdef ESP32S2
#define TIMERS_REG_BASE_ADDR	0x3F41F000
#define	GPIO_INTERRUPT_PRO		23
#define GPIO_INTERRUPT_PRO_NMI	24
#define DEDICATED_GPIO_IN_INTR	27
#define TG_T0_EDGE_INT			62
#define TG_T1_EDGE_INT			63
#else
#define TIMERS_REG_BASE_ADDR	0x3FF5F000
#endif

#define ESP_READ_REG(REG) (*((volatile unsigned int *)(((REG)))))
#define ESP_WRITE_REG(REG,DATA) (*((volatile unsigned int *)(((REG)))) = DATA)

#define TIMG0_T0CONFIG_REG		(TIMERS_REG_BASE_ADDR + 0x000)
#define TIMG0_T0LO_REG			(TIMERS_REG_BASE_ADDR + 0x004)
#define TIMG0_T0HI_REG			(TIMERS_REG_BASE_ADDR + 0x008)
#define TIMG0_T0UPDATE_REG		(TIMERS_REG_BASE_ADDR + 0x00C)
#define TIMG0_T0ALARMLO_REG		(TIMERS_REG_BASE_ADDR + 0x010)
#define TIMG0_T0ALARMHI_REG		(TIMERS_REG_BASE_ADDR + 0x014)
#define TIMG0_T0LOADLO_REG		(TIMERS_REG_BASE_ADDR + 0x018)
#define TIMG0_T0LOADHI_REG		(TIMERS_REG_BASE_ADDR + 0x01C)
#define TIMG0_T0LOAD_REG		(TIMERS_REG_BASE_ADDR + 0x020)
#define TIMG0_T0_INT_ENA_REG	(TIMERS_REG_BASE_ADDR + 0x098)
#define TIMG0_T0_INT_CLR_REG	(TIMERS_REG_BASE_ADDR + 0x0A4)

#define	TIMGn_Tx_EN				(1 << 31)
#define	TIMGn_Tx_INCREASE		(1 << 30)
#define	TIMGn_Tx_AUTORELOAD		(1 << 29)
#define	TIMGn_Tx_DIVIDER(X)		(X << 13)
#define	TIMGn_Tx_EDGE_INT_EN	(1 << 12)
#define	TIMGn_Tx_LEVEL_INT_EN	(1 << 11)
#define	TIMGn_Tx_ALARM_EN		(1 << 10)

#define TIMER0_GRP0_SETUP		(TIMGn_Tx_EN | TIMGn_Tx_INCREASE | TIMGn_Tx_AUTORELOAD | TIMGn_Tx_DIVIDER(8) | TIMGn_Tx_EDGE_INT_EN | TIMGn_Tx_ALARM_EN)

#define TIMER0					0x1
#define TIMER1					(0x1 << 1)



#endif
